### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by bep** [reitzig/actions-asciidoctor#15]
<img width="1210" alt="image" src="https://github.com/reitzig/actions-asciidoctor/assets/394382/367d5e50-675d-439f-9f04-8420773368de">

03fcc74cd74880b697950c4930c9ec8a67c69ecc == v2.0.1.

**Comment by reitzig** [comment]
Fixed with v2.0.2

Thanks for the nudge!
