### ISSUE TITLE
GitHub Actions Deprecating 'set-env' and 'add-path' commands

### ISSUE THREAD

**Issue by tnein** [reitzig/actions-asciidoctor#6]
The installation fails because of GitHub actions deprecating 'set-env' and 'add-path' commands.

Error: Unable to process command '::add-path::' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

`add-env` in:

https://github.com/reitzig/actions-asciidoctor/blob/9d6e321b10875548dc76621a02bc557e362dd784/dist/index.js#L219

`set-env` in:

https://github.com/reitzig/actions-asciidoctor/blob/9d6e321b10875548dc76621a02bc557e362dd784/dist/index.js#L197

**Comment by tnein** [comment]
sorry was only the case for v1.0.0
fixed in v1.0.1
by updating @actions/core
https://github.com/reitzig/actions-asciidoctor/pull/5

**Comment by tnein** [comment]
There is still some of the deprecated commands left.

In the v1.0.1 release:
https://github.com/reitzig/actions-asciidoctor/blob/v1.0.1/dist/index.js#L1021
https://github.com/reitzig/actions-asciidoctor/blob/v1.0.1/dist/index.js#L1037

As well as in v2.0.0:
https://github.com/reitzig/actions-asciidoctor/blob/v2.0.0/dist/index.js#L197
https://github.com/reitzig/actions-asciidoctor/blob/v2.0.0/dist/index.js#L219

This causes the following Errors:
>    Error: Unable to process command '::add-path::/home/runner/work/xs2a/xs2a/actions_asciidoctor' successfully.
  Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by reitzig** [comment]
I don't see any warnings in my [most recent runs](https://github.com/reitzig/today-i-learned/runs/1391501862) (well after that blog post). Did anything else change in the meantime? :thinking: Can you link to a run where you see that error?

**Comment by tnein** [comment]
Hm 🤔 It occurs in `Wrap asciidoctor with options`. This step is not run in your builds.
https://github.com/adorsys/xs2a/runs/1487558108

**Comment by reitzig** [comment]
Ah, true enough. As you [can see](https://github.com/reitzig/actions-asciidoctor/compare/v1.0.1...v2.0.0), the offending call was removed for 2.0.0.

I'm afraid I won't be able to support the 1.x line; I've always considered the option wrapping a dirty hack (which I needed to work around a deficiency in Hugo at the time). You don't seem to use that feature, anyway -- I recommend you upgrade?
