### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by gershnik** [reitzig/actions-asciidoctor#9]
Using `reitzig/actions-asciidoctor@v2.0.0` produces the following warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: reitzig/actions-asciidoctor@v2.0.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by reitzig** [comment]
Hej, thanks!

Don't see any warnings in my dog-food workflow; hope I bumped everything!
